INSERT INTO TESTDB.PUBLIC.USER ("ID", "NAME", "AGE", "ADDRESS") VALUES (NULL, 'Kirill', 28, 'Kherson');

INSERT INTO TESTDB.PUBLIC.USER ("ID", "NAME", "AGE", "ADDRESS") VALUES (NULL, 'Andrey', 33, 'Kiev');

INSERT INTO TESTDB.PUBLIC.USER ("ID", "NAME", "AGE", "ADDRESS") VALUES (NULL, 'Alex', 22, 'Nikolaev');
